### ISSUE TITLE
Body is null on RhttpStatusCodeException

### ISSUE THREAD

**Issue by sabin26** [Tienisto/rhttp#11]
**My API returns status 400 with an error message on the body**

Both `Client` from `package:http` and `FetchClient` from `package:fetch_client` allow the following:

```dart
final response = await Response.fromStream(stream);
if (response.statusCode >= 200 && response.statusCode < 300) {
    return response;
} else {
    // Decode the body and get the error message
    // body['error'] example: { 'error': 'Invalid email or password' }
   throw Exception(...);
}
```

But, Rhttp throws `RhttpStatusCodeException`. I catch the exception and try to get the error message from the body.

```dart
try {
    final response = await Response.fromStream(stream);
} on RhttpWrappedClientException (e) {
    // if e.rhttpException is RhttpStatusCodeException, get the body and try to decode it
   // body is null
}
```

The API response contains only the status code and not the body when used with Rhttp. But the response contains the body with error message when used with another http client.

I am using `RhttpCompatibleClient`.

```dart
RhttpCompatibleClient.create(
      settings: const ClientSettings(
        httpVersionPref: HttpVersionPref.http3,
        proxySettings: ProxySettings.noProxy(),
      ),
    );
```

**Comment by Tienisto** [comment]
Can you set `throwOnStatusCode` to `false`?

**Comment by sabin26** [comment]
Thanks ! Works as expected.
