### ISSUE TITLE
Provide compatibility layer for HttpClient of dart:io

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [Tienisto/rhttp#21]
i want to override httpclient with rhttp one on all of the app to make all packages use it 
```
class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
      RhttpClient client = RhttpCompatibleClient.createSync(); // this is doesnt work 
     return client
  }
}

void main(){
    HttpOverrides.global = MyHttpOverrides();

}
```

if there is an HttpClient variant that will be awesome since it can override all of the communication to use rhttp

**Comment by Tienisto** [comment]
Your type declaration is wrong:

```dart
// not RhttpClient
HttpClient client = RhttpCompatibleClient.createSync();
```

**Comment by abdelaziz-mahdy** [comment]
Oh well I didn't try that one, so it does implement the same class so it works as a replacement for it, that's very nice 

Thank you for the awesome package.

**Comment by abdelaziz-mahdy** [comment]
just tried that out it didnt work 

error:

A value of type 'RhttpCompatibleClient' can't be assigned to a variable of type 'HttpClient'.
Try changing the type of the variable, or casting the right-hand type to 'HttpClient'.

```
class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    HttpClient client = RhttpCompatibleClient.createSync();
    return client;
}
```

**Comment by Tienisto** [comment]
It seems that HttpClient is not the HttpClient from the http client but a different one.

You can jump to the declaration of RhttpCompatibleClient and you will see that it is a sub class of HttpClient

**Comment by abdelaziz-mahdy** [comment]
`class RhttpCompatibleClient with BaseClient` its not compatible with httpclient
its not the same i think :(

**Comment by abdelaziz-mahdy** [comment]
Will look into it and open a pr then let me know if the solution I come up with is good or not

**Comment by Tienisto** [comment]
Added `IoCompatibleClient` in `v0.8.0`
