### ISSUE TITLE
DNS resolver

### ISSUE THREAD

**Issue by fivetime** [Tienisto/rhttp#24]
Does rhttp support custom DNS resolution like Java's okhttp?

For example, I want to resolve the domain https://example.com/ to a specific IP address on my server, 123.123.123.123, instead of using the actual DNS resolution. Can rhttp achieve this?

**Comment by Tienisto** [comment]
The reqwest crate allows this (https://docs.rs/reqwest/0.11.18/reqwest/struct.ClientBuilder.html#method.dns_resolver) but there is no Dart API for it yet

**Comment by Tienisto** [comment]
Added `dnsSettings` in `v0.8.0`
