### ISSUE TITLE
Proxy settings to connect on charles proxy

### ISSUE THREAD

**Issue by llomerio** [Tienisto/rhttp#32]
Theres no way i can set the proxy on the rhttp client, and using the proxy set on system setting don't seems to work. how can i connect to charles proxy if i cant set the proxy?

**Comment by Tienisto** [comment]
In `v0.9.0`, you can now set custom proxies

**Comment by llomerio** [comment]
Custom proxy now works on current version, thank you!

another issue is ProxySetting is limited to adding proxy url manually, i cant set a global string to be the proxy url
