### ISSUE TITLE
Thank you for rhttp - Created a Talker logger integration

### ISSUE THREAD

**Issue by Shreemanarjun** [Tienisto/rhttp#34]
Dear @Tienisto 

I wanted to express my gratitude for creating and maintaining rhttp. It's an excellent package that has been incredibly useful in my projects.

I'm excited to share that, inspired by rhttp, I've created a logger integration called `talker_rhttp_logger`. This package combines rhttp with Talker to provide enhanced logging capabilities for HTTP requests and responses.

You can find the package here: https://pub.dev/packages/talker_rhttp_logger

I hope this contribution can be useful to the rhttp community. Thank you again for your fantastic work on rhttp!

Best regards,
Shreeman Arjun

**Comment by Tienisto** [comment]
Wow nice!
