### ISSUE TITLE
Does it support Certificate Transparency?

### ISSUE THREAD

**Issue by acn-masatadakurihara** [Tienisto/rhttp#37]
I am aware that Certificate pinning is supported this package, but I would like to confirm that [Certificate Transparency](https://en.wikipedia.org/wiki/Certificate_Transparency) is supported.

**Comment by Tienisto** [comment]
rhttp is a wrapper around [reqwest](https://crates.io/crates/reqwest). If they support it, rhttp does also. However, I could not find anything about it.

**Comment by acn-masatadakurihara** [comment]
@Tienisto 
Thanks for the useful information. As it turns out, reqwest's further referenced package (hyper) seems to support this, but it seems to require some handling, and I was not sure if that could be done from the rhttp layer. I will consider other means.
