### ISSUE TITLE
How to convert formData for use when calling the API to send multiple images

### ISSUE THREAD

**Issue by chopper985** [Tienisto/rhttp#7]
- I use FormData to upload multiple images to the server using Dio. How to do it for rHttp.

**Comment by Tienisto** [comment]
See https://pub.dev/packages/rhttp#-request-body (Multipart)

Copied from documentation:

```
await Rhttp.post(
  url: 'https://example.com',
  body: HttpBody.form({'key': 'value'}),
);
```

**Comment by chopper985** [comment]
I use `HttpClientAdapter` to configure from dio to rHttp, how to convert `MultiPartByte` to `MultipartItem` in fetch()

**Comment by chopper985** [comment]
Thanks, it's been resolved
